# Quick and Dirty Guide To Numpy


**So you want to learn about numpy?**

Numpy is an important library for anyone wanting to work with large scale datasets in Python.  Numpy arrays provide value because they are easier and faster to manipulate than traditional python lists.

### Why use numpy arrays instead of Python lists?

1. Saves you time as a programmer: when using lists, you have to use loops to apply a function to each element of an array.  In numpy, all common mathematical computations can be vectorized.  This leads to a much faster runtime, as well as fewer lines of code. 

2. Under the hood, numpy arrays use less memory, and are constrained to a single data type, which enables faster execution.

<img src="memory_diagram.png">

The figure above shows the memory diagram of a numpy array.  Python lists have special functionality where their elements don't all have to be of the same type.  As a result, under the hood python lists are actually an array of pointers that point to the actual array elements.  Hopefully, this fact provides some intuition as to why many operations run faster with numpy arrays as the underlying data structure! Neat!

### Let's get started!

In [15]:
#It's a common convention to abbreviate numpy as np
import numpy as np


## Stuff from last time

### Creating a Numpy Array
There are many ways to create a numpy array.  In general, the options are 
- converting other Python data structures to np.array format
- numpy functions that create new arrays (i.e. np.ones, np.zeros, np.arange)
- reading files from disk (in this class, mostly images)

Note that unlike lists, you can't create an empty numpy array

In [ ]:
# create a 1 dimensional array from a list: [1,2,3,4,5]
print("1 dimensional: ")
x = np.array([1,2,3,4,5])
print("Shape: ", x.shape)
x

In [ ]:
# Create a 2-d array from multiple lists: 
    # first row = [1,2,3,4,5]
    # second row = [6,7,8,9,10]
print("2 dimensional: ")
y = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print("Shape: ", y.shape)
y

In [ ]:
# you can create an array of any dimensions using np.zeros
z = np.zeros((3,3))
z

In [ ]:
#other handy things
identity = np.identity(3)
print(identity)

ones = np.ones((2,2))
ones

### Array attributes

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Take a look at the attributes associated with a numpy array, and then we'll explore how numpy arrays determine their type.

In [ ]:
print(identity.shape) #returns tuple of dimensions
print(identity.size) # returns total number of elements
print(identity.dtype) #the default dtype is float64

In [ ]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int64)  # Force a particular datatype

print(x.dtype, y.dtype, z.dtype)

### Accessing elements

Numpy offers several ways to index into arrays. When arrays are one dimensional, indexing works just like lists. When arrays are 2 or more dimensional, you specify an index for each dimension:

`value = array[row_index, col_index]`

In [ ]:
# Create a 2-dimensional array (matrix)
# [[ 1  2  3]
#  [ 4  5  6]]
a = np.array([[1,2,3],[4,5,6]])   
print(a)

# Access the 3 with array indexing
a_3 = a[0,2]
print("expecting 3, got: ", a_3)

# Access the 4 with array indexing
a_4 = a[1,0]
print("expecting 4, got: ", a_4)

Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array. Recall how slicing works in lists:

In [ ]:
# Recall list slicing:
l = [0,1,2,3,4]

print(l)
print("All elements of l: ", l[:])
print("All after 2nd element: ", l[2:])
print("All before 2nd element: ", l[:2])
print("All between 1st and 3rd element exclusive: ", l[1:3])

Now let's try slicing in two dimensions!

In [ ]:
print("a = \n", a)

# Access the 0th row of a:
a_row0 = a[0,:]
print("0th row expecting [1,2,3], got: ", a_row0)

# Access the 0th column of a
a_col0 = a[:,0]
print("0th column expecting [1,4], got: ", a_col0)

In [ ]:
# TODO: Create the following rank 2 array with shape (3, 4)
# [[ 1,  2,  3,  4]
#  [ 5,  6,  7,  8]
#  [ 9, 10, 11, 12]
#  [13, 14, 15, 16]]

# HINT: if you want to take a fancy shortcut, use np.arange() to create this matrix

b = np.array([[ 1,  2,  3,  4],
              [ 5,  6,  7,  8],
              [ 9, 10, 11, 12],
              [ 13, 14, 15, 16]])
print(b)

In [ ]:
# TODO: use slicing to pull out the middle two rows
b_rows = b[1:3,:]
print("middle two rows: \n", b_rows)

# TODO: use slicing to pull out the middle two columns
b_cols = b[:,1:3]
print("middle two columns: \n", b_cols)

# TODO: use slicing to pull out only the middle two rows and middle two columns,
# meaning a (2,2) array: 
# [[6 7]
#  [10 11]]
b_center = b[1:3,1:3]
print("center two columns and two rows: \n", b_center)


A slice of an array is a view into the same data, so modifying it will modify the original array.

In [ ]:
# [[ 1  2  3]
#  [ 4  5  6]]
a = np.array([[1,2,3],[4,5,6]])   
print("original a = \n", a)

a_row0 = a[0,:]
a_row0[1] = 100 # a_row0[1] is the same piece of data as a[0, 1]

print("new a = \n", a)

### Matrix Operations
Numpy makes it easy to do matrix operations on arrays, like multiply, invert, etc. Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

print("x = \n", x)
print(x.dtype)
print("y = \n", y)
print(y.dtype)



In [ ]:
#all arithmetic operations are applied to a matrix element-wise
print("Original x: ")
print(x)
print("\nx+1")
print(x + 1)
print("\nx*4.5")
print(4.5*x)
print("\nx/2.0")
print(x/2.0)

In [ ]:
# Elementwise sum; both produce the array
print("x = \n", x)
print("y = \n", y)
print("\nx+y:")
print(x + y)
print(np.add(x, y))

In [ ]:
# Elementwise difference; both produce the array
print("x = \n", x)
print("y = \n", y)
print("\nx-y:")
print(x - y)
print(np.subtract(x, y))

In [ ]:
# Elementwise product; both produce the array
print("x = \n", x)
print("y = \n", y)
print("\nx*y:")
print(x * y)
print(np.multiply(x, y))

In [ ]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print("x = \n", x)
print("y = \n", y)
print("\nx/y:")
print(x / y)
print(np.divide(x, y))

In [ ]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print("x = \n", x)
print("\nsqrt(x):")
print(np.sqrt(x))

In [ ]:
# Elementwise power; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print("x = \n", x)
print("\nx^2:")
print(np.power(x,2))

In [ ]:
# Will this multiplication operator do elementwise multiplication or matrix multiplication?
x*y

Let's practice these operations!

Given arrays x and y, write array z as a function of x and y: z[0] = x[0] - y[0], and z[1] = x[1] - y[1]. Use numpy operations!

Hint: think about how the 2 equations may be written with vector operations (such as those above), and that will translate cleanly to numpy 

In [ ]:
# TODO
x = np.array([1,3])
y = np.array([2,5])
z = np.array([-1,-2])

z_computed = x - y
print("Your answer: ", z_computed)
print("Expecting: ", z)
if z.all() == z_computed.all():
    print("Correct!")
else:
    print("Try thinking of a numpy function above with x and y that gets you equivalent to z")

Now, try using the numpy functions to calculate x = ((a+b)*c) - d

If you get stuck, try following the order of operations with the parenthesis and compute a+b first and verify by hand, and then proceed to (a+b)*c, and so on.

In [ ]:

a = np.array([1,3])
b = np.array([1,1])
c = np.array([2,1/2])
d = np.array([1,1])
x = np.array([3,1])

# TODO
#answer = 

print("Your answer: ", answer)
print("Expecting: ", x)
if x.all() == answer.all():
    print("Correct!")
else:
    print("Try thinking of a which numpy functions above with a,b, and c gets you equivalent to x")

### Axis-based operations

Now that we've covered 2d indexing, there's some important numpy functions that operate on a particular axis, so let's get hands on with sum()! Many numpy operations including sum, max, argmax, mean, standard deviation operate over a chosen axis of your array. 

Sum can sum all elements of the 2d array, or it can sum across each row, or sum down each column. 

Axis 0 corresponds to columns, and axis 1 corresponds to rows, just like indexing. When you apply an operation like sum over axis 0, that means axis 0 is being squashed into length 1 by the sum, max, etc. operation.

In [ ]:
#numpy arrays have builtin methods to calculate summary statistics such as std. dev., mean, min, max, sum
y = np.random.random(9).reshape(3,3)
print("std:", y.std())
print("mean:", y.mean())
print("sum:", y.sum())

print()
#you can also do these operations with respect to a particular axis
print("std (rows):", y.std(axis = 1))
print("mean (rows):", y.mean(axis = 1))

In [ ]:
# Sum of an array along various axes
x = np.array([[1,2],[3,4]])
print(x)
print()
print(np.sum(x))  # Compute sum of all elements; prints "10"
print()
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print()
print(np.sum(x, axis=1)) # Compute sum of each row; prints "[3 7]"

In [ ]:
# Sum of a vector doesn't need to specify axis since there's only one axis
x = np.array([1,2,3])
print(x)
print(np.sum(x))

Your turn!

In [ ]:
# Get hands-on with sum! Guess what the output will be and then run it to confirm
x = np.array([[1,2,3],[4,5,6],[3,2,1]])
print("x = \n", x)


In [ ]:
#np.sum(x)
# TODO:
guess = 
print("Your guess for np.sum(x): ", guess)
print("Actual = ", np.sum(x))

In [ ]:
#np.sum(x, axis=1)
# TODO:
guess = 
print("Your guess for np.sum(x, axis=1): ", guess)
print("Actual = ", np.sum(x, axis=1))

In [ ]:
#np.sum(x, axis=0)
# TODO:
guess =
print("Your guess for np.sum(x, axis=0): ", guess)
print("Actual = ", np.sum(x, axis=0))

### Demo
Imagine I want to apply the function $f(x) = x^2 + x -6$ to every emelent of an array

In [ ]:
#First let's try it with python lists
import random
random.seed(1)
h = 1000
w = 2

def func(x):
    return x**2 + x - 6

first_list = [[random.randint(-10,10), random.randint(-10,10)] for i in range(h)]
print(len(first_list))
first_list[:10]


In [ ]:
%%time
for i in range(h):
    for j in range(w):
        first_list[i][j] = func(first_list[i][j])

In [ ]:
first_list[:10]

### Now let's do the same thing with numpy arrays

In [ ]:
#By default, rand returns a rnadom number in the range [0,1) - so we normalize to get the values we want
array = np.random.rand(h* w).reshape((h,w))
array = array*20 - 10
print(array[:10])

In [ ]:
%%time
array = array**2 + array - 6

In [ ]:
#Check that it worked
print(array[:10])

### It's way faster!

### Some other useful manipulations
A complete list of possible array manipulations can be found here:
https://numpy.org/devdocs/reference/routines.array-manipulation.html

In [ ]:
np.concatenate((x,y), axis = 0)

In [ ]:
result = np.concatenate((x,y), axis = 1)
result

In [ ]:
#not an inplace operation, if you want it to persist you need to reassign the variable using =
np.transpose(result)

In [ ]:
#to invert a matrix use np.linalg.inv
x = np.array([[1,1], [1,0]])
np.linalg.inv(x)

### Numpy for Linear Algebra

#### Dot products

We'll first define vectors v and w. Recall that the dot product of two vectors is calculating by multiplying each corresponding value and then summing the result. Let's start by computing the dot product with a for loop

In [ ]:
v = np.array([1,2,3])
w = np.array([4,5,6])

print("v = \n", v)
print("w = \n", w)
print("expected dot product = 32")

# TODO: compute dot product of v and w with a for loop
# note: length of a 1 dimensional array  = len(array) or array.shape[0]

forloop_dotproduct = 0
for i in range(v.shape[0]):
    forloop_dotproduct += v[i]*w[i]

print(forloop_dotproduct)



In [ ]:
# TODO: compute dot product of v and w with numpy functions 
# hint: addition and summation are the key operations in a dot product

np_dotproduct = np.sum(v * w)
print(np_dotproduct)


In [ ]:
# TODO: two ways of using np.dot() to compute the same dot product
print(v.dot(w))
print(np.dot(v, w))

#### Matrix-vector product

We'll first define matrix M and vector v. Recall that matrix multiplication between a matrix and a vector involves computing a dot product between each row of the matrix M and the vector v. 

In machine learning, M is typically a matrix of learned parameters where each row corresponds to one of the output predictions, which is a weighted sum of the input features from v. The features v change for every new example but the weights M are applied to every example in training and testing data.



In [ ]:
M = np.array([[1,2,3],[3,2,1]])
v = np.array([4,1,2])

print("M = \n", M)
print("v = \n", v)
print("Result = \n[12, 16]")

In [ ]:
# TODO: get each row of M using array slicing
# M_row0 = M[?]
# M_row1 = M[?]

# TODO: compute the dot product of each row of M with v
# row0_dotproduct = np.dot(?)
# row1_dotproduct = np.dot(?)

# answer = 
print("np.dot matrix product = \n", answer)

In [ ]:
# TODO: get each row of M using array slicing
M_row0 = M[0,:]
M_row1 = M[1,:]

# TODO: compute the dot product of each row of M with v
row0_dotproduct = np.dot(M_row0, v)
row1_dotproduct = np.dot(M_row1, v)

answer = np.array([row0_dotproduct, row1_dotproduct])
print("np.dot matrix product = \n", answer)

In [ ]:
# Use numpy's built in functionality to get the same result
print(np.dot(M,v))
print(np.matmul(M,v))

#### Matrix-Matrix multiplication

In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[4,3],[2,1]])

print("A = \n", A)
print("B = \n", B)

In [ ]:
upper_left = np.dot(A[0,:], B[:,0])
print("upper left = ", upper_left)

upper_right = np.dot(A[0,:], B[:,1])
print("upper right = ", upper_right)

lower_left = np.dot(A[1,:], B[:,0])
print("lower left = ", lower_left)

lower_right = np.dot(A[1,:], B[:,1])
print("lower right = ", lower_right)

In [ ]:
print(np.dot(A,B))
print(np.matmul(A,B))

## New content!

### Numpy arrays, references, and *copies*
You may have noticed that it can be tricky to manipulate arrays in python because by default, python passed objects as references. In this section, we'll explain this behavior, and giving some debugging tools to use when confronted with related issues.

In [ ]:
array = np.linspace(1, 10, 10)
array


In [ ]:
dup = array
dup

In [ ]:
array[0] = 100
dup

In [ ]:
print(id(array))
print(id(dup))

Notice that the dup and array point to the same object!

How would we fix this?

Use the copy library, or np.array.copy

IMPORTANT: Using the slicing syntax [:] doesn't always work

In [ ]:
#slicing
array = np.linspace(1, 10, 10)
dup = array[:]
print(id(array))
print(id(dup))
array[0] = 100
dup

In [ ]:
#using copy
import copy
array = np.linspace(1, 10, 10)
dup = copy.copy(array)
print(id(array))
print(id(dup))
array[0] = 100
dup

In [ ]:
#using deep copy
import copy
array = np.linspace(1, 10, 10)
dup = copy.deepcopy(array)
print(id(array))
print(id(dup))
array[0] = 100
dup

Beware of copy vs. deepcopy!

https://docs.python.org/2/library/copy.html
<img src="shallow_copy.png">
<img src="deep_copy.png">

In [ ]:
#numpy arrays also have a builtin copy function
array = np.linspace(1, 10, 10)
dup = array.copy()
print(id(array))
print(id(dup))
array[0] = 100
dup

#### Let's try it with multidimensional arrays

Copy works!

In [ ]:
import copy
array = np.array(range(9)).reshape(3,3)
array = np.zeros((3,3))
array0 = [0,1,2]; array[0] = array0
array1 = [3,4,5]; array[1] = array1
array2 = [6,7,8]; array[2] = array2
print(array)

dup = copy.copy(array)
array[0] = [0,0,0]

print(array)
print(dup)


Numpy's native copy works!

In [ ]:
array = np.array(range(9)).reshape(3,3)
print(array)

dup = array.copy()
array[0] = [0,0,0]

print(array)
print(dup)


### Sorting


In [ ]:
array = np.random.random(10)
print("array = \n", array)
print("increasing sort = \n", np.sort(array))
print("decreasing sort = \n", np.sort(array)[::-1])

print("\ndecreasing sorted indices = \n", np.argsort(array)[::-1])
print("top 3 = \n", array[np.argsort(array)[::-1][:3]])


### Reshaping

In [ ]:
#when your reshape, by default you fill the new array by rows
x = np.linspace(1, 12, 6)
print(x)
x2 = x.reshape((3,2)) #does not reshape in place!
x2

### Broadcasting
The term broadcasting refers to how numpy treats doing arithmetic operations on arrays of different shapes.
When operating on two arrays, NumPy compares their shapes element-wise. Two dimensions are compatible when
* they are equal, or
* one of them is 1

If the dimensional are different, but one of them is 1, then numpy will apply the operation to each column on that axis

Check out the documentation for more details: https://numpy.org/doc/stable/user/basics.broadcasting.html

Broadcasting with scalars is pretty intuitive:

In [ ]:
x = np.array([[0,1,2]])
print("x = ", x.shape, "array:\n", x)
print("x+1 = ", (x+1).shape, "array:\n", x+1)

y = np.array(range(9)).reshape(3,3)
print("\n\ny = ", y.shape, "array:\n", y)
print("y+1 = ", (y+1).shape, "array:\n", y+1)


Broadcasting with scalars is really useful for normalization!

In [ ]:
x = np.random.rand(20,20)
#print("x = ", x.shape, "array:\n", x)
print("np.mean(x) = ", np.mean(x), "or x.mean() = ", x.mean())
print("np.std(x) = ", np.std(x), "or x.std() = ", x.std())

zero_mean_x = x - x.mean()
print("\nzero_mean_x.mean() = ", zero_mean_x.mean())

one_std_x = x/x.std()
print("\none_std_x.std() = ", one_std_x.std())

normalized_x = (x - x.mean())/x.std()
print("\nnormalized_x.mean() = ", normalized_x.mean())
print("normalized_x.std() = ", normalized_x.std())

You can also broadcast with vectors! We'll try a column vector first:

In [ ]:
x = np.array([range(9)]).reshape(3,3)
print("x = ", x.shape, "array:\n", x)

y = np.array([range(3)]).reshape(3,1)
print("y = ", y.shape, "array:\n", y)

print("x+y = ???")


In [ ]:
print("x+y = \n", x+y)
print("diff = (x+y) - x = \n", (x+y) - x)

Now let's broadcast with a row vector

In [ ]:
x = np.array([range(9)]).reshape(3,3)
print("x = ", x.shape, "array:\n", x)

z = np.array([range(3)]).reshape(1,3)
print("z = ", z.shape, "array:\n", z)

print("x+z = ???")


In [ ]:
print("x+z = \n", x+z)
print("diff = (x+z) - x = \n", (x+z) - x)

Watch out for one dimensional arrays! They'll broadcast like row vectors

In [ ]:
x = np.array([range(12)]).reshape(4,3)
print("x = ", x.shape, "array:\n", x)

y = np.array([0,1,2])
print("y = ", y.shape, "array:\n", y)

z = np.array([0,1,2,3])
print("z = ", z.shape, "array:\n", z)

print("x+y = ???")

print("x+z = ???")

Notice that x - (x+y) is not the same as just y because of broadcasting!

In [ ]:
print("x+y = \n", x+y)
print("diff = (x+y) - x = \n", (x+y) - x)

In [ ]:
print("x+z = \n", x+z)
print("diff = (x+z) - x = \n", (x+z) - x)

Broadcasting can also produce a different shape than either input:

In [ ]:
x = np.array([[1,2,3]])
print("x = ", x.shape, "array:\n", x)

y = np.array([[4,5,6]])
print("y = ", y.shape, "array:\n", y)
print("y.T = ", y.T.shape, "array:\n", y.T)

print("x*y.T = ???")


In [ ]:
print("x*y.T = \n", x*(y.T))


We can also use 1 dimensional arrays for outer products, since they *mostly* act as row vectors

In [ ]:
x = np.array([1,2,3])
print("x = ", x.shape, "array:\n", x)

y = np.array([[4,5,6]]).T
print("y = ", y.shape, "array:\n", y)

print("x*y = ???")

In [ ]:
x*y

In [ ]:
x = np.array([1,2,3])
print("x = ", x.shape, "array:\n", x)

y = np.array([[4,5,6]])
print("y = ", y.shape, "array:\n", y)

print("x*y = ???")

In [ ]:
x*y

### Real world example of why broadcasting is useful

In [ ]:
# Suppose we have a matrix where we want to normalize the rows to have mean zero
matrix = 10*np.random.rand(4,5)
matrix

In [ ]:
row_means = matrix.mean(axis = 1).reshape((4,1))
row_means

In [ ]:
matrix_zero_mean = matrix - row_means
print("matrix_zero_mean = \n", matrix_zero_mean)
print("matrix_zero_mean.mean(axis=1) = \n", matrix_zero_mean.mean(axis = 1))

### Using boolean masks
In numpy, when you compare two arrays, you get a boolean mask as the output.  You can then use this boolean mask to grab specific values in an array.

In [ ]:
array = np.array(range(20)).reshape((4,5))
print("array = ", array.shape, array.dtype, "array: \n", array)

filtered = array > 10
print("array > 10 = ", filtered.shape, filtered.dtype, "array: \n", filtered)

You can retrieve values in the array based on this mask!

In [ ]:
selected = array[filtered]
print("array[filtered] = ", selected.shape, selected.dtype, "array: \n", selected)

Or you can combine multiple boolean statements

In [ ]:
#you can combine boolean statements for more complicated operations
mask = (array < 5) | (array > 15)
print("mask = ", mask.shape, mask.dtype, "array: \n", mask)

selected = array[mask]
print("selected = ", selected.shape, selected.dtype, "array: \n", selected)

Can you select the elements of array that are multiples of 5 but greater than (exclusive) 5?

In [ ]:
mask = np.zeros_like(array, dtype=bool)
print("mask = ", mask.shape, mask.dtype, "array: \n", mask)

selected = array[mask]
print("selected = ", selected.shape, selected.dtype, "array: \n", selected)

In [ ]:
### SOLUTION ###
#you can combine boolean statements for more complicated operations
mask = (array > 5) & (array % 5 == 0)
print("mask = ", mask.shape, mask.dtype, "array: \n", mask)

selected = array[mask]
print("selected = ", selected.shape, selected.dtype, "array: \n", selected)

You can use selected elements from this boolean mask to change the original array. Try to take the multiples of 5 greater than 5 and multiply them by 10

In [ ]:
#you can combine boolean statements for more complicated operations
mask = np.zeros_like(array, dtype=bool)
print("mask = ", mask.shape, mask.dtype, "array: \n", mask)

new_array = np.copy(array)
print("new_array = ", new_array.shape, new_array.dtype, "array: \n", new_array)

selected = new_array[mask]
print("selected = ", selected.shape, selected.dtype, "array: \n", selected)


In [ ]:
### SOLUTION ###
#you can combine boolean statements for more complicated operations
mask = (array > 5) & (array % 5 == 0)
print("mask = ", mask.shape, mask.dtype, "array: \n", mask)

new_array = np.copy(array)
new_array[mask] *= 10
print("new_array = ", new_array.shape, new_array.dtype, "array: \n", new_array)

selected = new_array[mask]
print("selected = ", selected.shape, selected.dtype, "array: \n", selected)


We can do similar operations with np.where()!
https://numpy.org/doc/stable/reference/generated/numpy.where.html

Let's try to also select the elements greater than 5

In [ ]:
array = np.array(range(20)).reshape((4,5))
print("array = ", array.shape, array.dtype, "array: \n", array)


#indices = np.where()
#print("indices = ", type(indices), "length ", len(indices))
#print("indices[0] = ", indices[0].shape, indices[0].dtype, "array: \n", indices[0])
#print("indices[1] = ", indices[1].shape, indices[1].dtype, "array: \n", indices[1])

selected = array[indices]
print("selected = ", selected.shape, selected.dtype, "array: \n", selected)


In [ ]:
### SOLUTION ###
array = np.array(range(20)).reshape((4,5))
print("array = ", array.shape, array.dtype, "array: \n", array)

indices = np.where(array > 5)
print("indices = ", type(indices), "length ", len(indices))
print("indices[0] = ", indices[0].shape, indices[0].dtype, "array: \n", indices[0])
print("indices[1] = ", indices[1].shape, indices[1].dtype, "array: \n", indices[1])

selected = array[indices]
print("selected = ", selected.shape, selected.dtype, "array: \n", selected)


mask = array > 5
selected = array[mask]
selected

np.where() with 3 arguments acts differently: you define a boolean mask with your first argument, and the second argument defines the array you copy from if the condition is true, and the third argument defines the array you copy from if the condition is false.

Let's use this to round everything less than or equal to 5 to zero, and everything greater than 5 to 1!

In [ ]:
array = np.array(range(20)).reshape((4,5))
print("array = ", array.shape, array.dtype, "array: \n", array)

new_array = np.zeros_like(array)
print("new_array = ", new_array.shape, new_array.dtype, "array: \n", new_array)



In [ ]:
### SOLUTION ###
array = np.array(range(20)).reshape((4,5))
print("array = ", array.shape, array.dtype, "array: \n", array)

new_array = np.where(array > 5, 1, 0)
print("new_array = ", new_array.shape, new_array.dtype, "array: \n", new_array)



We just used scalars for the 2nd and 3rd arguments, but you can also use arrays! Let's replace all elements less than or equal to 5 with their squares and replace all elements greater than 5 with -1*array

In [ ]:
array = np.array(range(20)).reshape((4,5))
print("array = ", array.shape, array.dtype, "array: \n", array)
#squared_array = 
#print("squared_array = ", squared_array.shape, squared_array.dtype, "array: \n", squared_array)
#minus_array = 
#print("minus_array = ", minus_array.shape, minus_array.dtype, "array: \n", minus_array)


#new_array = np.where()
#print("\nnew_array = ", new_array.shape, new_array.dtype, "array: \n", new_array)



In [ ]:
### SOLUTION ###
array = np.array(range(20)).reshape((4,5))
print("array = ", array.shape, array.dtype, "array: \n", array)
squared_array = array**2
print("squared_array = ", squared_array.shape, squared_array.dtype, "array: \n", squared_array)
minus_array = -array
print("minus_array = ", minus_array.shape, minus_array.dtype, "array: \n", minus_array)


new_array = np.where(array > 5, minus_array, squared_array)
print("\nnew_array = ", new_array.shape, new_array.dtype, "array: \n", new_array)



### Linear Algebra
We can use the np.linalg module to do a lot of linear algebra stuff withpretty clean syntax.

For example, say we wanted to solve the linear system $$ Ax = b$$.

In [ ]:
A = np.array([[1, 1], [2, 1]])
b = np.array([[1], [0]])
#This function takes parameters A, b, and returns x such that Ax =b. 
x = np.linalg.solve(A, b)
print("solution = x = \n", x)  
print("Ax = \n", np.dot(A,x))
print("b = \n", b)            

#### How about more complicated stuff?
Imagine trying to find a line of best fit.

Linear regression finds the "line of best fit" by minimizing the residual sum of squares.

If we have n datapoints $\{(x_1, y_1), ... ,(x_n, y_n)\}$, the objective function takes the form
$$loss(X) = \Sigma_{i = 1}^n (y_i - f(x_i))^2$$ where $$f(x_i) = \theta_0 + \theta_1 x_1 + ... +\theta_n x_n$$

It turns out the parameters such that the loss function is minimized are given by the closed form solution

$$\theta = (X^T X)^{-1} X^T y$$

Let's see it in action!!!

In [ ]:
import matplotlib.pyplot as plt


In [ ]:
x = np.concatenate((np.linspace(1, 5, 10).reshape(10, 1), np.ones(10).reshape(10, 1)), axis = 1)
y = x[:,0].copy() + 2*np.random.rand(10) - 0.5
plt.scatter(x[:,0], y)

In [ ]:
theta = np.linalg.lstsq(x, y, rcond=None)[0]
print(theta)

In [ ]:
plt.scatter(x[:,0], y)
plt.plot(x[:,0], x[:,0]*theta[0] + theta[1])

In [ ]:
theta = np.linalg.inv(x.T.dot(x)).dot(x.T).dot(y)
print(theta)

How does this relate to transformations? Let's try!

Our slides on transformations: https://drive.google.com/file/d/1isX1q9X31akdeIJwdbP5xNqn78xzhlXb/view

In [16]:
x = np.random.rand(10,2)*10
print("x = ", x.shape, x.dtype, "array: \n", x)
# Homogeneous coordinates!
x_homogeneous = 
print("x_homogeneous = ", x_homogeneous.shape, x_homogeneous.dtype, "array: \n", x_homogeneous)

translation = np.array([3, -5])
scaling = 2

y = (x *scaling) + translation
# Add noise
y_noisy = y + np.random.rand(10,2)*0
print("\ny_noisy = ", y_noisy.shape, y_noisy.dtype, "array: \n", y_noisy)
# Homogeneous coordinates!
y_noisy_homogeneous = 
print("y_noisy_homogeneous = ", y_noisy_homogeneous.shape, y_noisy_homogeneous.dtype, "array: \n", y_noisy_homogeneous)

# Fit with lstsq!
H = np.linalg.lstsq(x_homogeneous, y_noisy_homogeneous, rcond=None)[0]
print("\nH = ", H.shape, H.dtype, "array: \n", H)
error = np.round(np.dot(x_homogeneous, H) - y_noisy_homogeneous, decimals=8)
print("Error = np.dot(x_homogeneous,H) - y_noisy_homogeneous = \n", error)



SyntaxError: ignored

In [17]:
### SOLUTION ###
x = np.random.rand(10,2)*10
print("x = ", x.shape, x.dtype, "array: \n", x)
# Homogeneous coordinates!
x_homogeneous = np.concatenate([x, np.ones((10,1))], axis=1)
print("x_homogeneous = ", x_homogeneous.shape, x_homogeneous.dtype, "array: \n", x_homogeneous)

translation = np.array([3, -5])
scaling = 2

y = (x *scaling) + translation
# Add noise
y_noisy = y + np.random.rand(10,2)*0
print("\ny_noisy = ", y_noisy.shape, y_noisy.dtype, "array: \n", y_noisy)
# Homogeneous coordinates!
y_noisy_homogeneous = np.concatenate([y_noisy, np.ones((10,1))], axis=1)
print("y_noisy_homogeneous = ", y_noisy_homogeneous.shape, y_noisy_homogeneous.dtype, "array: \n", y_noisy_homogeneous)

# Fit!
H = np.linalg.lstsq(x_homogeneous, y_noisy_homogeneous, rcond=None)[0]
print("\nH = ", H.shape, H.dtype, "array: \n", H)
error = np.round(np.dot(x_homogeneous, H) - y_noisy_homogeneous, decimals=8)
print("Error = np.dot(x_homogeneous,H) - y_noisy_homogeneous = \n", error)



x =  (10, 2) float64 array: 
 [[0.79674385 0.88365502]
 [2.84209383 1.62185751]
 [3.5990535  7.46510644]
 [2.07226094 6.89104397]
 [1.71922719 9.98589271]
 [5.80360217 4.10095815]
 [2.66727262 7.5242551 ]
 [8.71956479 3.90952378]
 [9.12033466 4.14834314]
 [1.77145371 9.27497125]]
x_homogeneous =  (10, 3) float64 array: 
 [[0.79674385 0.88365502 1.        ]
 [2.84209383 1.62185751 1.        ]
 [3.5990535  7.46510644 1.        ]
 [2.07226094 6.89104397 1.        ]
 [1.71922719 9.98589271 1.        ]
 [5.80360217 4.10095815 1.        ]
 [2.66727262 7.5242551  1.        ]
 [8.71956479 3.90952378 1.        ]
 [9.12033466 4.14834314 1.        ]
 [1.77145371 9.27497125 1.        ]]

y_noisy =  (10, 2) float64 array: 
 [[ 4.59348769 -3.23268996]
 [ 8.68418765 -1.75628498]
 [10.19810699  9.93021289]
 [ 7.14452187  8.78208794]
 [ 6.43845439 14.97178542]
 [14.60720434  3.20191629]
 [ 8.33454525 10.0485102 ]
 [20.43912959  2.81904757]
 [21.24066933  3.29668628]
 [ 6.54290742 13.54994249]]
y_noisy_

In [18]:
# Compare with theoretical H
scaling_matrix = 
translation_vector = 
homogeneous_row = 
print("\nscaling_matrix = ", scaling_matrix.shape, scaling_matrix.dtype, "array: \n", scaling_matrix)
print("Translation_vector = ", translation_vector.shape, translation_vector.dtype, "array: \n", translation_vector)
print("homogeneous_row = ", homogeneous_row.shape, homogeneous_row.dtype, "array: \n", homogeneous_row)
H_theoretical = 
H_theoretical = 
print("H_theoretical = ", H_theoretical.shape, H_theoretical.dtype, "array: \n", H_theoretical)
print("H = ", H.shape, H.dtype, "array: \n", np.round(H, decimals=8))
print("Diff = H_theoretical - H = \n", np.round(H_theoretical - H, decimals=8))

SyntaxError: ignored

In [20]:
### SOLUTION ###
# Compare with theoretical H
scaling_matrix = np.eye(2)*scaling
translation_vector = translation.reshape(2,1)
homogeneous_row = np.array([0,0,1]).reshape(1,3)
print("\nscaling_matrix = ", scaling_matrix.shape, scaling_matrix.dtype, "array: \n", scaling_matrix)
print("Translation_vector = ", translation_vector.shape, translation_vector.dtype, "array: \n", translation_vector)
print("homogeneous_row = ", homogeneous_row.shape, homogeneous_row.dtype, "array: \n", homogeneous_row)
H_theoretical = np.concatenate([scaling_matrix, translation_vector], axis=1)
H_theoretical = np.concatenate([H_theoretical, homogeneous_row], axis=0)
H_theoretical = H_theoretical

print("H_theoretical = ", H_theoretical.shape, H_theoretical.dtype, "array: \n", H_theoretical)
print("H = ", H.shape, H.dtype, "array: \n", np.round(H, decimals=8))
print("Diff = H_theoretical - H = \n", np.round(H_theoretical - H, decimals=8))


error = np.round(np.dot(x_homogeneous, H) - y_noisy_homogeneous, decimals=8)
print("Error = np.dot(x_homogeneous,H) - y_noisy_homogeneous = \n", error)
error_theoretical = np.round(np.dot(x_homogeneous, H_theoretical) - y_noisy_homogeneous, decimals=8)
print("Error = np.dot(x_homogeneous,H_theoretical) - y_noisy_homogeneous = \n", error_theoretical)


scaling_matrix =  (2, 2) float64 array: 
 [[2. 0.]
 [0. 2.]]
Translation_vector =  (2, 1) int64 array: 
 [[ 3]
 [-5]]
homogeneous_row =  (1, 3) int64 array: 
 [[0 0 1]]
H_theoretical =  (3, 3) float64 array: 
 [[ 2.  0.  3.]
 [ 0.  2. -5.]
 [ 0.  0.  1.]]
H =  (3, 3) float64 array: 
 [[ 2. -0. -0.]
 [ 0.  2.  0.]
 [ 3. -5.  1.]]
Diff = H_theoretical - H = 
 [[-0.  0.  3.]
 [-0. -0. -5.]
 [-3.  5.  0.]]
Error = np.dot(x_homogeneous,H) - y_noisy_homogeneous = 
 [[ 0. -0.  0.]
 [ 0. -0.  0.]
 [ 0. -0.  0.]
 [ 0. -0.  0.]
 [ 0. -0.  0.]
 [ 0. -0. -0.]
 [ 0. -0.  0.]
 [ 0. -0. -0.]
 [ 0. -0. -0.]
 [ 0. -0.  0.]]
Error = np.dot(x_homogeneous,H_theoretical) - y_noisy_homogeneous = 
 [[ -3.           5.          -2.02804357]
 [ -3.           5.           0.41699393]
 [ -3.           5.         -26.52837173]
 [ -3.           5.         -28.23843704]
 [ -3.           5.         -44.77178197]
 [ -3.           5.          -3.09398423]
 [ -3.           5.         -29.61945762]
 [ -3.           5. 

### Vectorizing equations
In classes with CS 231N, you'll want to write your equations in matrix format because it's more effecient to run operations in parallel. Here's an example: This can be really tough, so here's an example:

Suppose we didn't know that linear regression had a closed form solution. We could also solve the problem above using gradient descent.

The gradient descent update rule looks like this:
$$\theta_{t+1} =\theta_t - \alpha \nabla_{\theta} L(\theta, X)$$

So we need to find the gradient with respect to $\theta$. Recall that a gradient is a vector of partial derivatives.  So let's start by finding just one partial derivative.

$$\frac{\partial}{\partial \theta_j}L(\theta, X) = \Sigma_{i = 1}^n 2(y_i - f(x_i))(-x_i[j])$$ where $$f(x_i) = \theta_0 + \theta_1 x_1 + ... +\theta_n x_n$$

Now the task is to get this into matrix format! Our theta vector is $\theta = [\theta_0,\theta_1] \in R^2$. Notice that our residuals can be written as a vector, $y - f(\theta, X) \in R^n$.

In matrix multiplication, we dot the row of the first matrix with the columns of the second matrix.  A sum (like above) can oftern be expressed as a row times a column.

$$\theta_{t+1} =\theta_t - \alpha X^T (y - f(X, \theta))$$




    

### In numpy

np.repeat (https://numpy.org/doc/stable/reference/generated/numpy.repeat.html) and np.tile (https://numpy.org/doc/stable/reference/generated/numpy.tile.html) can be really useful for this!

# Making Plots in Jupyter Notebook
A Matplotlib figure can be categorized into several parts as below:
    
**Figure:** It is a whole figure which may contain one or more than one axes (plots). You can think of a Figure as a canvas which contains plots.

**Axes:** It is what we generally think of as a plot. A Figure can contain many Axes. It contains two or three (in the case of 3D) Axis objects. Each Axes has a title, an x-label and a y-label.

**Axis:** They are the number line like objects and take care of generating the graph limits.

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
x = np.arange(10)**2
print(x)
plt.plot(x)
plt.show()

In [ ]:
plt.figure(figsize = (15,15))
plt.plot(x)
plt.title("This is a graph")
plt.xlabel("this is the x label")
plt.ylabel("this is the y label")
plt.show()

### Additional Resources
https://www.youtube.com/watch?v=8Mpc9ukltVA

https://jakevdp.github.io/PythonDataScienceHandbook/02.01-understanding-data-types.html

https://towardsdatascience.com/matplotlib-tutorial-learn-basics-of-pythons-powerful-plotting-library-b5d1b8f67596

https://scipy-cookbook.readthedocs.io/items/ViewsVsCopies.html

https://www.geeksforgeeks.org/copy-python-deep-copy-shallow-copy/